from __future__ import annotations

# Operational storage retention and query bounds.
AGENT_TASK_LIST_DEFAULT_LIMIT = 20
AGENT_TASK_LIST_MAX_LIMIT = 100
AGENT_TASK_EVENT_LIST_DEFAULT_LIMIT = 200
AGENT_TASK_EVENT_LIST_MAX_LIMIT = 500
AGENT_TASK_EVENT_RETENTION_COUNT = 200
AGENT_TASK_RECEIPT_LIST_LIMIT = 112
AGENT_TASK_RECEIPT_RETENTION_COUNTS = {
    "summary": 64,
    "diagnostic": 32,
    "trace": 16,
}
AGENT_TASK_ESTIMATE_HISTORY_LIMIT = 100
AGENT_TASK_ESTIMATE_SAMPLE_LIMIT = 20
AGENT_TASK_RECEIPT_MAX_BYTES = 8 * 1024
AGENT_TASK_RESULT_MAX_BYTES = 64 * 1024
AGENT_COMMAND_EVENT_MAX_BYTES = 32 * 1024
PATCH_OUTPUT_RETENTION_DAYS = 7
RUN_TRACE_RETENTION_DAYS = 90
WRITING_SESSION_RETENTION_DAYS = 180
WRITING_SESSIONS_PER_PROJECT = 50

# Team enrollment and browser authentication.
TEAM_INVITATION_TTL_DAYS = 7
TEAM_CODE_FAILED_ATTEMPT_LIMIT = 5
TEAM_SESSION_IDLE_DAYS = 14
TEAM_PUBLIC_AUTH_REQUEST_MAX_BYTES = 4 * 1024
TEAM_ENROLLMENT_CODE_MAX_LENGTH = 128
TEAM_MEMBER_TOKEN_MAX_LENGTH = 64
TEAM_SESSION_TOKEN_MAX_LENGTH = 80
# Exact inventories are rendered into the bounded server CLI contract. Thirty-two
# identifiers fit in one nonsecret field; larger consequence sets must be reduced
# before an operator can confirm them safely.
MEMBER_REMOVAL_PREVIEW_MAX_ITEMS = 32

# Durable canonical chat history queries and summary labels.
CHAT_PAGE_DEFAULT_LIMIT = 50
CHAT_PAGE_MAX_LIMIT = 200
CHAT_TITLE_MAX_CHARS = 120
CHAT_PREVIEW_MAX_CHARS = 240

# Staged agent command mailbox, and the Auto-research broker that fronts it.
# The broker deliberately outwaits the client. Whichever side gives up first owns
# the diagnostic the agent reads, and the client's is the one that correctly says
# "unavailable" rather than blaming the request. Keep the grace positive, or a
# slow RCP starts reporting a perfectly good command as a broker-side failure.
COMMAND_MAILBOX_TIMEOUT_SECONDS = 30.0
COMMAND_MAILBOX_POLL_SECONDS = 0.2
COMMAND_BROKER_RESPONSE_GRACE_SECONDS = 5.0
AUTO_RESEARCH_PROMPT_FILE_MAX_BYTES = 16 * 1024
AUTO_RESEARCH_APPLY_MAX_PER_TURN = 32
# One turn's in-turn Applies plus the end-of-turn settlement disposition. The
# capture side and the storage side must agree, so it is derived once here.
GRAPH_UPDATE_HISTORY_MAX_COUNT = AUTO_RESEARCH_APPLY_MAX_PER_TURN + 1

# Temporary agent-created preview artifacts.
CHAT_ARTIFACT_MAX_COUNT = 8
CHAT_ARTIFACT_MAX_FILE_BYTES = 16 * 1024 * 1024
CHAT_ARTIFACT_MAX_TOTAL_BYTES = 32 * 1024 * 1024
# One paid Auto-research mail wake carries only this bounded prefix. The byte limit
# stays well inside the reusable stage mailbox's per-file artifact ceiling.
AUTO_RESEARCH_MAIL_MAX_MESSAGES = 64
AUTO_RESEARCH_MAIL_MAX_BYTES = min(1024 * 1024, CHAT_ARTIFACT_MAX_FILE_BYTES)
AUTO_RESEARCH_LIFECYCLE_MAX_NOTICES = 50
AUTO_RESEARCH_LIFECYCLE_MAX_BYTES = 256 * 1024
# Temporary human-provided chat inputs. Keep these independent from output artifact
# limits even while their initial bounds happen to be the same.
CHAT_ATTACHMENT_MAX_COUNT = 8
CHAT_ATTACHMENT_MAX_FILE_BYTES = 16 * 1024 * 1024
CHAT_ATTACHMENT_MAX_TOTAL_BYTES = 32 * 1024 * 1024
RUN_STAGE_RETENTION_DAYS = 7
REMOTE_ARTIFACT_READ_TIMEOUT_SECONDS = 30

# Human-requested repository source previews. These bytes are held only for the
# request and are never copied into RCP storage.
REPOSITORY_PREVIEW_MAX_BYTES = 2 * 1024 * 1024
REPOSITORY_PREVIEW_TIMEOUT_SECONDS = 30

# Live patch self-validation through the run-stage file mailbox.
PATCH_SELF_CHECK_MAX_COUNT = 6
PATCH_SELF_CHECK_POLL_SECONDS = 0.2
PATCH_SELF_CHECK_TIMEOUT_SECONDS = 30
PATCH_SELF_CHECK_MAX_REQUEST_BYTES = 16 * 1024 * 1024

# Scratch-only correction rounds in the recovery ladder. Seed/Refresh, Work, and the
# Auto-research worker each hand validation errors back to the same live session at
# most this many times before the run is rejected. One number, one policy: raising it
# here raises it everywhere, which is the point.
PATCH_CORRECTION_MAX_ROUNDS = 2

# Durable external-work watchers.
WATCHER_CHECK_TIMEOUT_SECONDS = 15
WATCHER_POLL_INTERVAL_SECONDS = 5
ACCEPTANCE_AGENT_JOB_SECONDS = 2.0
WATCHER_CHECK_WORKERS = 4
WATCHER_ERROR_MAX_CHARS = 4000
WATCHER_HEALTHY_INTERVAL_SECONDS = 2 * 60
WATCHER_ERROR_BACKOFF_SECONDS = (2 * 60, 4 * 60, 8 * 60, 15 * 60, 30 * 60)
WATCHER_SCHEDULE_JITTER_RATIO = 0.10
WATCHER_GROUP_DIAGNOSTIC_ERROR_COUNT = 5

# Agent context budgets.
CHAT_CONVERSATION_LIMIT = 120
RUN_INLINE_SESSION_LIMIT = 40
RUN_INLINE_SESSION_BYTES = 12 * 1024
REFRESH_DELTA_MAX_ENTRIES = 50
REFRESH_DELTA_MAX_BYTES = 16 * 1024

# Rebuildable display/source caches and remote source operations.
PROJECT_DISPLAY_SNAPSHOT_MAX_BYTES = 16 * 1024 * 1024
REMOTE_STATE_HEAD_PROBE_INTERVAL_SECONDS = 3.0
REMOTE_STATE_HEAD_PROBE_TIMEOUT_SECONDS = 5.0
REMOTE_STATE_RECONCILE_WINDOW_SECONDS = 2.0
REMOTE_SOURCE_CACHE_TTL_SECONDS = 30 * 24 * 60 * 60
REMOTE_SOURCE_CACHE_MAX_COUNT = 256
REMOTE_SOURCE_CACHE_MAX_BYTES = 1024 * 1024 * 1024
SESSION_SLICE_CACHE_TTL_SECONDS = 14 * 24 * 60 * 60
SESSION_SLICE_CACHE_MAX_COUNT = 512
PROJECT_TRANSFER_SOURCE_PROBE_TIMEOUT_SECONDS = 30
SESSION_SLICE_CACHE_MAX_BYTES = 512 * 1024 * 1024
REMOTE_SOURCE_OPERATION_TIMEOUT_SECONDS = 180
SOURCE_ORIGINAL_COPY_BUFFER_BYTES = 1024 * 1024

# Personal-to-team transfer archives fail visibly when an inventory or diagnostic
# cannot be represented. Scientific payload bytes have no aggregate size ceiling;
# later capture/relay owners stream them with this fixed buffer instead.
PROJECT_TRANSFER_INVENTORY_MAX_ENTRIES = 100_000
PROJECT_TRANSFER_DIAGNOSTIC_MAX_COUNT = 128
PROJECT_TRANSFER_DIAGNOSTIC_MAX_CHARS = 4000
PROJECT_TRANSFER_MANIFEST_MAX_BYTES = 64 * 1024 * 1024
PROJECT_TRANSFER_COPY_BUFFER_BYTES = 1024 * 1024
PROJECT_TRANSFER_STABLE_READ_ATTEMPTS = 3

# Canonical-state advisory lock acquisition and holder lifecycle.
STATE_LOCK_ATTEMPT_TIMEOUT_SECONDS = 30.0
STATE_LOCK_HOLDER_STOP_TIMEOUT_SECONDS = 5.0
STATE_LOCK_POLL_INTERVAL_SECONDS = 0.2

# Server and frontend-build lifecycle timings.
SERVER_SHUTDOWN_TIMEOUT_SECONDS = 45.0
SERVER_LOCK_DEFAULT_TIMEOUT_SECONDS = 0.0
SERVER_LOCK_OWNER_READ_ATTEMPTS = 10
SERVER_LOCK_POLL_INTERVAL_SECONDS = 0.05
SERVER_HEALTH_REQUEST_TIMEOUT_SECONDS = 2
SERVER_INSTALL_PROBE_TIMEOUT_SECONDS = 30.0
SERVER_INSTALL_ACCOUNT_TIMEOUT_SECONDS = 300.0
SERVER_INSTALL_SOURCE_TIMEOUT_SECONDS = 300.0
SERVER_INSTALL_BUILD_TIMEOUT_SECONDS = 30 * 60.0
SERVER_UPDATE_REHEARSAL_TIMEOUT_SECONDS = 30 * 60.0
SERVER_UPDATE_CHECKPOINT_TIMEOUT_SECONDS = 30 * 60.0
SERVER_INSTALL_SERVICE_TIMEOUT_SECONDS = 60.0
SERVER_INSTALL_HEALTH_TIMEOUT_SECONDS = 15.0
SERVER_INSTALL_HEALTH_POLL_INTERVAL_SECONDS = 0.25
SERVER_INSTALL_HEALTH_RESPONSE_MAX_BYTES = 64 * 1024
SERVER_GIT_CREDENTIAL_TIMEOUT_SECONDS = 30.0
SERVER_GIT_PROBE_TIMEOUT_SECONDS = 120.0
SERVER_PROJECT_CHECKOUT_TIMEOUT_SECONDS = 120.0
SERVER_BACKUP_CONFIGURATION_TIMEOUT_SECONDS = 30.0
SERVER_RESTORE_DECRYPT_TIMEOUT_SECONDS = 30 * 60.0
SERVER_CONTROL_IO_TIMEOUT_SECONDS = 5.0
SERVER_CONTROL_BACKUP_CAPTURE_TIMEOUT_SECONDS = 30 * 60.0
SERVER_CONTROL_UPDATE_MAINTENANCE_TIMEOUT_SECONDS = 30 * 60.0
SERVER_CONTROL_UPDATE_VERIFY_TIMEOUT_SECONDS = 5 * 60.0
SERVER_CONTROL_PROVIDER_CHECK_TIMEOUT_SECONDS = 60.0
SERVER_CONTROL_PROJECT_PROVISION_TIMEOUT_SECONDS = 30 * 60.0
SERVER_CONTROL_ACCEPT_POLL_INTERVAL_SECONDS = 0.2
SERVER_CONTROL_STOP_TIMEOUT_SECONDS = 5.0
SERVER_WEB_BUILD_MAX_FILES = 8192
SERVER_WEB_BUILD_MAX_BYTES = 512 * 1024 * 1024

# Online team-server backup capture. Entry and diagnostic limits fail a capture
# visibly; they never truncate scientific history and call the result complete.
BACKUP_INVENTORY_MAX_ENTRIES = 100_000
BACKUP_STABLE_READ_ATTEMPTS = 3
BACKUP_COPY_BUFFER_BYTES = 1024 * 1024
BACKUP_SQLITE_PAGES_PER_STEP = 256
BACKUP_SQLITE_BUSY_SLEEP_SECONDS = 0.01
BACKUP_RECEIPT_MAX_BYTES = 64 * 1024 * 1024
BACKUP_REMOTE_EXPORT_TIMEOUT_SECONDS = 30 * 60.0
BACKUP_DIAGNOSTIC_MAX_COUNT = 128
BACKUP_DIAGNOSTIC_MAX_CHARS = 4000
BROWSER_OPEN_DELAY_SECONDS = 0.7
WEB_BUILD_TIMEOUT_SECONDS = 60.0
WEB_BUILD_STOP_TIMEOUT_SECONDS = 5.0
WEB_BUILD_POLL_INTERVAL_SECONDS = 0.05
