/// The RCP window loads the backend's own origin, which the ACL treats as remote,
/// so every app command needs an autogenerated permission the capability can grant.
const COMMANDS: &[&str] = &[
    "desktop_status",
    "desktop_reconnect_backend",
    "desktop_show_ready",
    "desktop_list_team_connections",
    "desktop_configure_server_operator_route",
    "desktop_probe_server_operator",
    "desktop_run_project_provision",
    "desktop_open_project_provision_terminal",
    "desktop_run_project_transfer",
    "desktop_prepare_project_transfer",
    "desktop_load_project_transfer",
    "desktop_advance_project_transfer",
    "desktop_run_incoming_project_provision",
    "desktop_read_target_project_provisioning_options",
    "desktop_export_project_transfer",
    "desktop_select_project_transfer_export",
    "desktop_open_project_transfer_terminal",
    "desktop_finish_project_transfer",
    "desktop_discard_project_transfer_export",
    "desktop_remove_team_connection_metadata",
    "desktop_remove_team_member_token",
    "desktop_connect_team_tunnel",
    "desktop_enroll_team_connection",
    "desktop_add_existing_team_connection",
    "desktop_establish_team_session",
    "desktop_navigate_team",
    "desktop_return_to_personal",
    "choose_repository_folder",
    "desktop_start_dictation",
    "desktop_stop_dictation",
    "open_artifact_preview",
    "open_episode_report_preview",
    "open_repository_file_preview",
    "download_artifact",
    "open_external",
    "request_quit",
    "check_for_update",
    "apply_update",
];

fn main() {
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("macos") {
        cc::Build::new()
            .file("src/dictation.m")
            .flag("-fobjc-arc")
            .flag("-fblocks")
            .compile("rcp_dictation");
        println!("cargo:rustc-link-lib=framework=AVFoundation");
        println!("cargo:rustc-link-lib=framework=Foundation");
        println!("cargo:rustc-link-lib=framework=Speech");
        println!("cargo:rerun-if-changed=src/dictation.m");
        cc::Build::new()
            .file("src/https_trust.m")
            .flag("-fobjc-arc")
            .flag("-fblocks")
            .compile("rcp_https_trust");
        println!("cargo:rustc-link-lib=framework=Security");
        println!("cargo:rerun-if-changed=src/https_trust.m");
    }
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(COMMANDS)),
    )
    .expect("failed to run tauri-build");
}
