export const NOTICE_TIMEOUT_MS = 3000;
export const CHAT_USER_MESSAGE_COLLAPSE_THRESHOLD = 320;
export const CHAT_SCROLL_BOTTOM_TOLERANCE_PX = 48;
export const NODE_DETAIL_RESIZE_MIN_WIDTH = 360;
export const NODE_DETAIL_RESIZE_MIN_HEIGHT = 320;
